// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBG3PGMSRZnp-97EgRnk-TNaHVZ6EICpqI',
    appId: '1:1001281401892:web:f1176dd499e5bec4b0d4b1',
    messagingSenderId: '1001281401892',
    projectId: 'cargo-go-b5f77',
    authDomain: 'cargo-go-b5f77.firebaseapp.com',
    storageBucket: 'cargo-go-b5f77.firebasestorage.app',
    measurementId: 'G-WM9B66FK2V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD37YdGfyW3DFpQl6v48mLfGrjBds78iOI',
    appId: '1:1001281401892:android:b70989512cee13dfb0d4b1',
    messagingSenderId: '1001281401892',
    projectId: 'cargo-go-b5f77',
    storageBucket: 'cargo-go-b5f77.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDdKdXnzW6mOPfKvT_U3nT67DvBRKz3YVY',
    appId: '1:1001281401892:ios:8ca7b7ce2b5f0c20b0d4b1',
    messagingSenderId: '1001281401892',
    projectId: 'cargo-go-b5f77',
    storageBucket: 'cargo-go-b5f77.firebasestorage.app',
    iosBundleId: 'com.example.cargoGo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDdKdXnzW6mOPfKvT_U3nT67DvBRKz3YVY',
    appId: '1:1001281401892:ios:8ca7b7ce2b5f0c20b0d4b1',
    messagingSenderId: '1001281401892',
    projectId: 'cargo-go-b5f77',
    storageBucket: 'cargo-go-b5f77.firebasestorage.app',
    iosBundleId: 'com.example.cargoGo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBG3PGMSRZnp-97EgRnk-TNaHVZ6EICpqI',
    appId: '1:1001281401892:web:8882614dc275d754b0d4b1',
    messagingSenderId: '1001281401892',
    projectId: 'cargo-go-b5f77',
    authDomain: 'cargo-go-b5f77.firebaseapp.com',
    storageBucket: 'cargo-go-b5f77.firebasestorage.app',
    measurementId: 'G-D9KB9KYDGQ',
  );
}
